apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: device-plugin

helmCharts:
  - name: amd-gpu
    repo: https://rocm.github.io/k8s-device-plugin/
    version: v0.21.0
    namespace: device-plugin
    valuesFile: values.yaml
