apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pki

helmCharts:
  - name: step-certificates
    repo: https://smallstep.github.io/helm-charts
    version: v1.29.0
    releaseName: step-certificates
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - ./pvc.yaml
  - ./ingress.yaml
  - ./sealed-step-certificates-ca-password.yaml
  - ./sealed-step-certificates-certs.yaml
  - ./sealed-step-certificates-config.yaml
  - ./sealed-step-certificates-provisioner-password.yaml
  - ./sealed-step-certificates-secrets.yaml
  - ./sealed-step-certificates-ssh-host-ca-password.yaml
  - ./sealed-step-certificates-ssh-user-ca-password.yaml
