---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-provisioner-password
  namespace: pki
spec:
  encryptedData:
    password: AgAMJsyNfGpPrWSpAhqT1aP2TG9tRu4WveeP3J7czKpUnBssoa892tOPLOx5gWB2l7bjFJMBnEKTmIzimO2xVS4Ike5uPd+DGLZoV6tbMl0246qbuBEZqeioDDzHdMZMkl/wbiWUJYwmAcSIttPDJbafzn8baf+wsJX/iZiL1fj4uj1lY4fET+Ro0STQK8TpkOYRxv3H0qBSGGtO0rztCOPq3smVnr+qc56pqFkwc7BASWYDUsUOulkaWwJk9XyvixO+9oBsox1tbLMSldhZ3dajXVcEKdlbbM0wnz9qRhyUi2pkwW8JmlTlg08lJ2UaRtgtsh/FKEcHpkDvM4+htZTMOTfIYX3o6mLjdxZQRUu1VLdhCXsVAKfIBXbMrtwghFaf8FDNcuUz275T6EaiNJeNGGtP9t/C2UbX5sAF6YT2AteS9cdjC3ysXtjLfjJpzMJqZZ/r9lIotrrqam+cjgtpQbOYyu2SjMDjuCEisn0fxkGw9Dy1HXtgOpeQChLfJC2ICGCpyhDaoTym3slHqQJDN3pI1+pTaPKX8FiPZbZobFXJXCkupNYuYmmAZp83pZ5EPegPRC8FG2cwMAERGA6Kon1slADmrExbLwVKQ8RnwBtPfU8fTOnJoXwYhyjGX6UzBsY3v1gYQIlT1UNAorzn5B3iL7f8VuNm+V83kN0KNEgsdoEUnzEVrJ78qq4wywqi9aGxydwGQUCIYzSq/04SV7qNHA==
  template:
    metadata:
      name: step-certificates-provisioner-password
      namespace: pki
    type: smallstep.com/provisioner-password

