---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-provisioner-password
  namespace: pki
spec:
  encryptedData:
    password: AgB2/LuBaWN5RjmFU74Cr/a0vY5eFDivSXlnBN4KvEg1rtTwvtPoK5ZUCMMUeC6P9po0bw98C4dICbSHGYppKr7z5jIUcY3sQYHUTFFFCFDvRI6Lgg/t9U5mTe/s58aE/bdi1e16P2ZUglVYwLLFdBDnOnw859wfod5T3q9K5ePEcG1+DGuWcsFV8Y98Y2wLDfGyRqeLPgWcV0bCv29caHigxltZQtJNRvm3BYCwC4iuzXdy0g5OaUhwty9C3fmK6a78XqzLmSS9tsGmEOZqweQlxBpqjDnUiKvJVaaM+QCsSi7IsfgnWhXtIGY0VwqHENPYhqgPj9uBY3T2hNkJyUpjak0B+zp42TqiVSu1PJH/GA7rmFil0lF0GwjZ3oKGDxMmCKM5Jr7up3g/3SYwm3Swp4ClS1f+eVntxK9yFFEvJMaU7YWP50Jy2X829lAu9GMcCC4v7ySg9ml9oOYxmjb2afuCGo8PGRnqcQKNEp2jLRMAGbkHMZh/hy5oqAcwY7VfwagKkDo82dDoTNRsJQ6gEwNj0SauZiMMdnOej1jq1Fov+Xa9H0S2dlFWSawyDj+CHJRhFteTix8tWWKue+N4kdAjFJRT23RFXo/hfDOd2Hy9oi6WOfDBR8nZH1EllNRdWT4QPBffW1bQVzX3ph8/19CpoY2noY/RkCtmCuXrziSlI5T2rasvSQ5JOVt76TLyPrf8IH1FiSHbEfAXprSVeRNuXQ==
  template:
    metadata:
      name: step-certificates-provisioner-password
      namespace: pki
    type: smallstep.com/provisioner-password