---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-user-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgBOKHYuaqmESbqLnsDc0sCGdi5G7pDEP0hvShGJEqSjFrWdJj/4kIOTxUd1eVDjgLANMw0nKc4zyvvkDhhM6lgMfaJjuetlTm+9DlpfLl2DF0LkjhkPYFi1WTjtLSjfDAlgPa30jH9MXrs398gG3Z2cpO17zjA5R18cQonyOjbLNW0KobmRKdQ5f8cLWisJEuPu5PMnD7ZfVX+9HX0UWcDSrxGjVpASVmhif5CMweNHtp5kCZzAeMF2IFGhNIHLPY6zl7BHXS2eSXEVkLg0YzGY/YWpZ/IxGARjgQINAmuieVb2KVMrjwib2nZJzxndq3S/6X8Wt+PzD1hl9vI9qhCR2MVUrX7Pn5irAa6WscoCb0jDQ6+5OderlUpWp8LuXzM5K5q5sNUE1spAUwauqqXYYYdnGO+a8A77dQ71upL2JCZCbxbjeY72NsdKs3Ws/3MGO0BYNfTgzHQwn5SBlzUZgas2psDf9PWbbG/wCqxOFomTwcdk3hR3AHxnTHjj6WsaoR5KyI4DxXVASm0Z3namnGikn4LDJ1ZNNKYJqji5wKE1kUN0O2+9Cn9Xp1PzGWELb6RCo1ob2VLlb32d8DBgKvKG3+KWjRcZmvRN+PGelJeojsg9Lzk1ZOMlJhLqqgCd49ttCTXbRdWzpYc18oXw9kKP2jxqKvRIrsd2QBY/0rWf1In2FL7TjuXiF/OOu6c9gEWW3rLxoIDUhmHMxWfM00UWkg==
  template:
    metadata:
      name: step-certificates-ssh-user-ca-password
      namespace: pki
    type: smallstep.com/ssh-user-ca-password