---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgABkLLFV0frEQFey6AgjFP9/6Tb8As8Iz9OWGHHEBkeT8V1izRcfKCZ0AZM0K1BhT+8ZvgjpU0Z4Huaem0rGdpQNGU9pc0U+b504TZXQZQRAF55Qg0FaiN8WZTWHiJvK3TS3PQjIAvVWoXWjaNOz6DGgL1u608/g7eaO8pAEieu/G/6QorHIUAvohq3PbVoH6fu3XRHNlM6oi3TqSt2Iw0fIZM9T3V2c6R9hev2jkLsPTgzuhtyElz4M/lbPFU0Tzs+833IWCRWwaPvowrF4mMgu9ZZHVR4gFgK4L0h941MCthytrgzOxjc9133ZFdTL8Jvs4C4FPMvaeVYAKcdttH/P9C84Ul+NYL7M4KhvnNmoXtZJQlPcwPrzXPx0yvREX7LtuJ41EejE0v5uB98LBM9ANBHPeRbAEGOVLbvY2ebFFcEHCwy1X4XCpEliEvt4i/BkY8VZ3u5pnYgXJTsxXr7KNZAwiwv+1l2qW9eqa3HIvTM7+v+mogHXVFke7dSIqN1wcPxGjQisp3F/zjpJiNJ2rPpX5MjKoqkPL2Gvr+C+n6G6g4ysc9OWONelAQX26naucDK/45NKDBf9sf7LBnJDkPoOwU3/W3yPWmrYLmIPYHIXLcEIPhiyPcoHVAOj4L+vgVld8p4wUBaqizd4WHv9NSYhQyQ4HvLGxRo2biZqVmohi7enEkLk4PwlCoRCIK5Bdk/oPf6bQEIMqG5CR7r79Lmpw==
  template:
    metadata:
      name: step-certificates-ca-password
      namespace: pki
    type: smallstep.com/ca-password