---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-host-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgBN+m4MhtT6xwH4Cno0yElec58K9w1xP2QedzLpDh+kZVf9M8/tWsR0OYDUG9X+zsC8JJxfsc/bmtqObHiLwQTSpsFeSUupBOT3KBZAverWhM23VC+GZcEk8e4BdZVrPEtlgl2CXzmUuuSBV56b1O72hvn0NHpjfjoaX7RG0vLYD/haG2fCkr+H8IyV7N19rLn072dcscE2Pu4dErq7AguK9jQcjotuFtwwfWEzHhP0fEtYGUoTTJvBlzkZHoODflPTV8IOahgNSGE3YLrxYc9LKackGmQ9z8/LH1nKkZ/y5GAmgcJSKhu81+pMeREoeHRlORp8Z59OjFZrxqemLEzYufVBZC8mzwxR3XB15PkoQLCNxNMqLv53Vh+hRNbnma6Achx5zYESt6qSfkfxyVSpDwQQR30uW2KSUG8kTN6xK/z+F9bfs4TGPBkBMGqphymTBFIxcl0tMsrfZUUCZHOIO5jtSqJ5DgLPNP273B4+NEe65+8vKnUfVTPH9tKkSkCOMMCsr5pUgKy5gwEN6f9qA0b3nPRBuC3abn2scb+4uMpZXpR7SpApLCgKUOioP30xkOp9VwSBZGwaMqQRdwOHqxlYNdTibZ7+V0uRazdxHLnht8rJS1OJhB6D9e1IfdX5YCrwnuRBtRAv7EMCrLvITFT7GilXweRmIZGU5vn4sxbeaIEio9L0xtRz7+Mb8YB/qJCdZU8o6asi6QjMKRN9IIG92S0=
  template:
    metadata:
      name: step-certificates-ssh-host-ca-password
      namespace: pki
    type: smallstep.com/ssh-host-ca-password