---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-host-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgBkmnrGwbNwJpHycqs5GChTUG21Z7bx1JC96W7blKZHpUKOXcVxgrVz0Lgj3kld+TsSKvuOeOUQDFoRDiOC4TRW9f+R9Sa71A4i4n4bnhLCZRRhjbmMWzvGpujwp5WBCSKkCmwEbUIMxmze4vN0YhU38k1prWDpY7axzlpKPtNJpjD1RB578PL1KiJ//tS9mtamQbZVc9CTQZtm/E4ZkEYxkgCWAzCmeD+Nn1HnU651FV0QZm6mQF2PhyPEWhEpUGAakPxaJUANFWjS9gcxQF7z6T/6dUIGxJNWd4BdAKGzSIriVdRKt8yWanyoKfCj9MZ4nv43sbhgwHF2+agv2mWh8rxaTYVZZ06T/wGRlFFMfIVM5I4dOrvq64bg/7Z3TbAOL4i4zy/vjOleMWiVz5U3Kmh4gf4HNFrD6xPhtRNte8E7JCpOtuVxsbc7GiCdHNwZsnmFTErVs0e+fLiq/5nmVoeO0lFLyQPe0Iyz3ZuIrKaoTvq+vVL7PQlwYMhCw07lRw7lBEvPZPuHOLa+LWgNEHX9Cztwk9ytNrYO8xQw1r68hC9iUZPE9SrCQaHzkfclv5X2DYgBISL1OefkeHmCeP8G8eALVXyTK1yBiXGR8BBvGxLl/DhIlzb3NXLi2EqvP+NHfH/WD8QcdtBSseKROFAGBzX6ON+mJ6iqSujvgSg0k7TQreprsboTP/56xrTWbTDBbqzO8IEcB2jkXbYHyUp8SQ==
  template:
    metadata:
      name: step-certificates-ssh-host-ca-password
      namespace: pki
    type: smallstep.com/ssh-host-ca-password