---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-user-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgCH1uvXkIEY6o4HOjfZnQF5EwlakNRTJ/xIxEWlewbxpWlXlY+yWe4v/zfw6DD38GnmwI0ajziO/uaYvKqGY9pBha2rt1f8hnQULX6Ap39C57ikgxM+qSf/MWmKFmoBV+F9sWvEG0BHHnvzu/OsdI2qtvtMlCL8LXfWN0LrPJ9kDQFfi2ryT5IK+lEdbnAi7J1OpI6urZ8L5GHUby7WVsd1VOFABVl6unfC7zpav2rm/+QkTSH0hQXzm58kgvGfDnwaz6BsTTHAAc3iXA71fSmhPrWXbEjGguLUO2g8fqI1Gotp+4g4mT6j9Gq+dPMcIXr9HSrdSXzO/IJ+fs5W02Sc2vuCcpbFSMQN2Jn2QpVzYuNRfAnE8b+59pRV8qPnjEP3loKaitLxP8ynbPSkgUsxIIUU4/ZHzaACd5hQX69IHxOb8SkosViiUer+eRvtgyCjWwp/lKdKbKrIYly/PRCFPiGC1Jozm7CFSh+4CsnadqIb2BpQqz7yJw0hxa6G9+arKgtkWWWgPv4R+IVfplQkJQw9JCTgGc7h/OAdeNfU6JhRcqYWSdAORTNxBglt1Ltouf9pubdowjbv/B+NnpGwG/HTr3A7ylaZpBYgBgb9iCMDt/r3QekY2bZ64TXnueY8lygZKSb2X5PxyiItOeV04gKLzbvmam1ys6i9s/A0A0iAx3xQcJsiqEP+Nhv+A+PwuzcvDqfDAeXWfOehHJRST/i2Hw==
  template:
    metadata:
      name: step-certificates-ssh-user-ca-password
      namespace: pki
    type: smallstep.com/ssh-user-ca-password