---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-user-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgBqt5bzrZxUvJvANK7Z7xGGvwjNqyHN+cn5HgflTuEiUn/yLw40oPy7Qp34IHPD0mxXTkjdVO8uNqOaGe/jeU9ECOh0L35eS7D/KuAI3h8bZWHqc+Cq8ACJATPuJGIPnDqFQdsvEvvML7fREBXMYU9pAUq1+oXT/tGP4pbhKJNVqzcyh9EiLqpYe9uUslhKD65HpJ/fBGwPCv8FMenWotEFhaBqXcsQv94elIFyJSzo+WWllFic1TsSGL4MMpLQSJf7qt+baqOoKkL5/vM/uHocqr8zxm7jxSKCHtHb2oDNSA+jH6+kBv7s1b2Y30YybJCHOmIAvDRMUIcOG3IjGoPWwNsePyh2qOTRJW/Sldd/jBqI3tndjZ4z5oyNrm4E58gWLMX+Rvli9sCxPY6aslMCnoEgQYLYShqXzM6P+jIc3X/eMELcz87wwM5UcOTiYWIHoAGXzmYbfhfHAKL8FsBH+aNI1YkuICDvDsBxQ3y5j1YFgPt3ZoKodTHAGiPmrIBCZv3dXj6DAPBWicghW4c2jawHxvSVQaM7+TQ7WPG+YBz/CU+gZv1ouK1ICfxUn2pzQyu+tbtx/435D5RHbpbiTtueDptQlGO4JmL2b4azjwlkMkrgFOiPpS7YTatwnIdroZGYSiJdsVczPEOhWAgN5OohXo4FGCQmg5s19x9VZT2q3BuN+3DIVv8D/fAep1FWGao20bVp1+AtOgXK5V2+cjsnsTg=
  template:
    metadata:
      name: step-certificates-ssh-user-ca-password
      namespace: pki
    type: smallstep.com/ssh-user-ca-password