---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ssh-host-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgAYDX9jsV3yCJYn/xgq7xe3loUuo49MPOMQcpT+yl8UGGLS3llQC+pIJ03s7FudgfBqhC2dZjOlcnjF8CrLG7BNRcDnLfTrgLGzowXZi8msqCdfYGu6W/V7TIr+zi7ea8J4DDmK7Vs7j1LUVJswvjaP3PeUL5f3mcJdbhWbS4y7Pk5tIUaRCC0XkERXf1pAGs4h54Dpil1EXkvxMBkZ5wzBRK4BQe0dCVd6wSe5mXMIUYbox8Ec1gDfMEmFcT0Q6FP0GlQ4F1gG66KXN2QHTkF1DL12mGeDZVxdeALMDrP813OUpl0Y21724s/Mg4K8lgKV/lbUyrM4c/+FjJ8XSWouFYhIsqsdZU2YdZRvc/PxjVXDoeOnnjkfbUbE9L1rm+VusPgs/ItR67VO4/zXp1AtduAeIPtGFfrGZvNZFUSSCzjC33MylamZzhYoRovTYXUswX1PVo/DcpzVSCjXeyhJ0ffWnvA1toHA8DYBhdDSXBttzr4nSWIFxyPGl2Oci7eoyKd0KQFuvNsx1pYd0OnukY2CyCdcnKl755WDLjvOJSiUwqKLQAGQ2HDziDnHNfWal+PcMh+JhqEL4C3897i0eN9HiZwlOMk+3gvO8hPByDSw8fV3WnNTIBgQR+PEtf5GBr2WDOncz/+5CiyQqE6Cu5+W3b926BR7cpl2FG7RxmCu7cz50PKFQd7MPB0L6qM0iMNrE4vRQY3JSQpvkGpi+eQIug==
  template:
    metadata:
      name: step-certificates-ssh-host-ca-password
      namespace: pki
    type: smallstep.com/ssh-host-ca-password