---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-provisioner-password
  namespace: pki
spec:
  encryptedData:
    password: AgBu+DH8behVzqacZTXHtPGNSnEnaOaOnWpKh13gtU6N7LlOLrAAV3f0kIIshfaepF6b49P/srZNPf2Ixl2EoWTEkSjUIvxW4kNOXfGay/MkiKsqeIR4dMkBjPdQOQjkUftMIv1t2VYp+tFiUDkiCZqksupYpyxCTQIkmmlWLmccdCzP4RovMnhKn/pmLYcXt9AQQJFg+uDEkPcVheNzdN4X9xmi25+dmpS4jd5Ny/Qk37r7Qe6jJCBadBhw+QJjGimuNtMSla2AfG7U6ckntk0UpyQyXnpw5ACXjueE6yKeNAGr9yigpMYlFvWN1kKntco26uz09cUQFXgcanbO2dkl3Z7CE65Mcj6YkQI6XfbxlTc9OfZJIiS9SEIXn9itw/QQup+q86LFUdSTMdUfLlZ3MCNKKlVpEgYN5/of4HUwdMyxnUkGQosGvZp+oPP22wgZH5w7gCK2yiJGeTt7PPe9uglxP5y1oNNjkvEfXTl48j8rL0ggHFkksdHrhskXImfQn+2ayTXbDJUiSI30gmQdROkNoO/9eGClEAbU9708SVYusdUoK3d30wwL4tJlq9g1oP6N3n9zdFpk0gpSW214IVxWZFCWymXsXEs1hL0C39cDgGne3pQwTb3yCYsm7gyjHyCFbhnkMXsUg0r1IqgAJloJ5375tGq3Ani5OH4XMz+pZR8Gq6Un4lbf6iFOJKWBMM4bDDB9uRWBZVQOvF0kmMGpvw==
  template:
    metadata:
      name: step-certificates-provisioner-password
      namespace: pki
    type: smallstep.com/provisioner-password