---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgAZNiJ+Rx9oohwZgJPFFYJM0K84uCnmdMKmTr82yUiX9xmYoPPPM/oHSdaUWGMDdjQej3CMDc0/aA+SZ5jV3nHG2SRr/vdRe1rTpSW37xXLXCSd/uGLVET2Jj8qbWISepip/Sc346A65sWBR9bDTvtcJnjNZ0ssSSptoJfJ7SXd617JcMpou/xnfVdZl50TEpiXvI3mVBg0aRsJnU+xicPJ5R9xEO3B+99Qm8+495KH4F7DCgSXqQ+JF1SpOd/6n9KNGJyLzOPMGF3WAgr7mSzwalzUqhL2wFLXP8wMfUqU2l/Yp+WW6k1IXJA2t3CCLd6ODreZ7eu61+sLp5TT4ATF5RlbspCiephUbUMpmhoIAIcTrBsLTm+Gd3hO9vxTf+Ti928B3zBOJxIvgDe7klFMrq0Cu5VggoxLUblNTyVHVGK/PKO+Fp8ZJKMywsTn1nIrMwVtYiHOiYUhq1IbZT61SyCTXGZbGUsVppimpzfmmLU9WIOg7auYmxO2P9yfqpkCKtHpP1492vSethyVTMqSh3OJ2e94C8WeJ5UPaS94Wuq1jrtSR17FHVTvDV1z8OvRKKgpj22HflKg79dhSFskUxqul5rKc0DjmC5eFIGmHuQVsNCcZAckkOK+ZO1RXRfUCb/7UrQTl8eetA7CS9hNhM6+hHXMn6V8DkVcF/rfm55IHlC0K2qwaXaG/nib1cWr67gunftFRIHMxLmjlc3MsXJHtA==
  template:
    metadata:
      name: step-certificates-ca-password
      namespace: pki
    type: smallstep.com/ca-password