---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: step-certificates-ca-password
  namespace: pki
spec:
  encryptedData:
    password: AgAw9J7fINN7Na1eBR2+D0IWD2hZ3xTrvw9vYo71H/ifL2m2FkGZMTIUBQPckFcXN8P7hxFpCxA19M+MfZVOjB8WY3yrjBHcPhg4WLTon2MzHCFxmSvp3F20aQ2x46hlKkOb8mGi88nNoSyJ83b0G+WOFdZ94rGB8pBT4WFPJ3HyOmhhp6t+Ic8NXeKwzFOZc9wCVZ6KBFrGsrCEiy39hp7gNsgTdCLh4jD/0KJaEo6H/2P8zb9kz3I8sQPh7l9hDB27+KR6ciF32R8qauz3Sepc6pu+BvIu+hChm43XvVfqMW7Cld8GxACt87J9KjuYzifk1hp70lxSFG3+AV+ziDjXmiR4eYDXkgO4j43yzwCg9VkLzGv08/sBX69Ob2qHRTCjkHmwmJVYC0mB0/q6cIeK3bNHC5pERmDhjjoB9IVGau4UvhSWR8TPzAPdRG5R+FQeu/Y08xFWrFDBvBn/nGfG5dv+Zz5oJN/VIVjF+5EqrPflI4F1GCk0fW4KF+57BbhtWB9yFMhD9+ostc/eOBTZ1kwaA1HQ/Kw0rbrImvt2c8kZ2rTUPD2JcO/IrcnbB8o6ttRDbqpOM+pKZz1wufKj/C+EQcX8hU9Msu/Euh4kmIKTmp0dEN32bRB3/+bViumpmaviBB+1/bNsnm4aMUvTjjh5P81T0bnwV+2pH3KcyC5rsWuUwqh7w5d/Pom2MmzSsyXSo53UnShwhHAoTsH4M6itBMA=
  template:
    metadata:
      name: step-certificates-ca-password
      namespace: pki
    type: smallstep.com/ca-password