apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: v4.4.0
    releaseName: openebs
    valuesFile: values.yaml

resources:
  - openebs-zfspv.yaml
