openebs:
  engines:
    local:
      lvm:
        enabled: false
    replicated:
      mayastor:
        enabled: false
    rawfile:
      enabled: false

  loki:
    enabled: false

  alloy:
    enabled: false

  lvm-localpv:
    lvmNode:
      kubeletDir: /var/lib/k0s/kubelet
  zfs-localpv:
    zfsNode:
      kubeletDir: /var/lib/k0s/kubelet
  rawfile-localpv:
    node:
      kubeletPath: /var/lib/k0s/kubelet
  mayastor:
    csi:
      node:
        kubeletDir: /var/lib/k0s/kubelet
