---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-login
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBFI9T5mEW0gvsn73quXJ97PzYxSTHYAuighye4qN1gKksVTFlRG6umO49jXUtsuj4PicHgQCBHkhYx7ltO+8SzdORs1ubwloQAz6nOO82ON4RJdJV08rMQBrSUl/L/DeHD548FnHJZmBfYZeBvSbKESXgNT4oqrkqlijeH9Df5kFiI+rbkeJkwXsBpw63Bl9BRuJsrdOC/I8KH0yXvvKyY/8ETcjo/7S1OJFK2edsBDySWqLdyLCi+L27hAiWbyrCT/BvdUsXxhbuIpeezsdpS7z6QPGmJsTJ2//gSSlvNoNljHihvc1AyLhFMpGF54Q7yYxKaoxE85SFQ2V+8sZrRr/+7zoujV/zUHJJp+EiI1MkrZlUGTr16MtdX1MeA+3FO7JPuMCWXBMsZxnhaXdXkL0Ns/EdMFiY2RjQds4C/0GGR5scsBU3bxClED6QSH5J/8uHoyBow/C2jT0oZ6KX5SN5OtqZX/7iERc6FODwZ0xNEOPBXorK0IGWuRVOwbghU3mnTmxfGkxUGJXsNj8BjRpNRYXoW47cxiZr4SjNEHCXbQ0qqM9AozVMA4lcXmEdfEsv2QOrGKHK08feZQm1oFvqEMwDmnyauOrgvLMN4GfHqmqAg80ZE8p9oNp8xN8WRQO3BsxyzfihRe0JxBiTIBnt/xtCjMJv3hpWJXmYV/QR3K4N2UBURek2YQ6ln3xSnHVKtEaeU1F6UL3fopoq5CrVTAw==
    admin-user: AgAPUjLmoo7p8J14S8uNVn+WWoxuALz5WQCwlTKwaxPImP39Jf1iu0uzcggqiU3UTOYmUIG7Pp1yZAK8wYXW4eqMXN6PPBao0p0SfPEsm4Jkv6a3kNx35stLMU56R/lDrS5ec1nXvtDimPj1ms1r5wSXeE+f6ZHQFKc/Qq2cevXK5cxIgE5LXssm1T9u6Igr5Fvq30HDJeO48fZEg02hzWVNz6P70aapf7PmHRWsO3bwEKLogG3TD/qyXyE88Am/DDIMNnWXTPndve/CUm8jQJHb93HeFm6wo0obO5IvplLirJmngvW5rh3bp49dFl7iaACKjd3M6zh7qWMbzGRFjII3bebfApSWnPn5XlwBxXNV7Nhrgy7RGV/J6qe5w6wPMLPCQd4PUAOsGCihDRII+nfH4n4j+u596yWOpvgUBSxJqcOCN62VswrdLpfiUKREyAaOeF3TMCV7/G/uj3SqLapmR+g1TnMIORMQLBPXzeR3YfRNnUSPQuc5sO2tXbp+fwJPxHRM1ywdG6bnCeBzMlehgT861kG/J60KHehpZFLGfD8+eJZkH49yu7hCUVsk4RtnpQHjGQFgiymE0yZYsuguInFeGr+VwbkIPG5InsftixNa+MlokcQjE5gymh+N+OewZq4gOkeLeZffWl9H9fNii7Iws4ssffq8bDw5R98xpItjZHbGWX1Dxky+/W73KKbIw9l/kg==
  template:
    metadata:
      name: grafana-admin-login
      namespace: monitoring
    type: Opaque