---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-login
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCP3O3q8x4+wABgG9h+RXjHuIBbj/s7Y+d2p7A10YqmYkkvNbBG/uBA4B4khcP1lwuo4BxOe83K6W/GA14mFtpUGvD9b3goYKXCc/uQBeSA81QZJ6/gzVnF0ou1ckYEp7K54aS37JHNx7ML90bObvaukr5XdtC/7ey+iw9hX2DUr7hFvQilFMJWY6l1eGe15o52Z56PdASaAPdtgvnrVQtGTN7kZb77tuSwaY2TNnQiHPd7rkmcpU6h4LwLO4Nn7VsBoap8dMSyE7VBHExaJE3+cvcAHyWPcEPVqcOAefrHjWWkjpqudkXt/nMMU7TzURemEGXlFTqkN+yfgeOsFehVvkd5uOqimd7G/tlvRuz8socgZsTFPIokM5xKF1ivzQvFeD+BaFvcFJcW8QsD3dzvX5U2ufzI4luncF/XuNqPeQAgCwucoPi4Gpz88B7JsZfH2UDZ+8Wy2h7+l1oNvNGuQv292RWZAGg3TSjHlHmi+dutbucIHFmfyTrg+5NWhvHqepX75q01tCMZIfGLU2ZYCHx8eVOLFF41zY4FvZ71TQ2T5YTgEgEAr2ip0sp3dyfV7C3os9mp3E31y/Wfu9EeH0bV/EUKq1Koh3ZfRtzbZilbxdqyx7jZa4BSZ6RbeJgdnoJGfSBV+XURfyOxdWeI0XLs1ib2I/lrRJ0MiVwMz/n8QfCxeE6lzQDPVknE1OfSVQqX52oN+VhQHLXOpDgYLWLSKQ==
    admin-user: AgBzUIOHxfbD3bPLli+sky/l4EtAAsLCLxW3wuYG4kGpMUDKx7kB7ECbbDcsdP2Fw2LTojGbpLaN/N2UrbGVdFvmGv36PKfPzkR5iYc9DCuTuGUsfkplwDe7AuSl+Lm/vYDbe38EMc7g0tU1CO+Lqb3CV0heKCJYrBF+8Zn/lrGZ45O6q+ee9YBiKuK8d+j9bHpQ0QPfR9UTjaQ9nBHTXVDuYAsItARsx4ir4W6wtu2F3c/xtj7ooZglcqlopJDxkY0O19YTOCPOwpN9If0dBnM6gkvAMfRPXxNcsn2pXn34up1fpQYapUfs8GsCgtedpDxTm+LT7JjDOjqtbHTBhaG6tUaoQJixSncV2D5a/2taLEQfkngWcpGYgz+iVcO9kaXVN+vYIeuaJdJHHDlwLjZWjC5SX5CRS/QTib5RZRgPz2LtF172XFXKAezo0f89Y6z2kNgBTqQQNZ2oc6rCFrCNtWLFt+arluNmPJrot+axmJJo9ibhrPiKkFa6cSd4LcYzTq3PGzd1kxkivkVQ+ibphw9/kfJq5BHksJy4G7pYZ84Lgi/sL/ahdd4Ce5yEP1HIKjd/1G6mYO2i99r/JYNgpIC1Ns0mzLZOEtOXIe2aqqpvj8cAdJbrqKWDPSik851HsS2SHGwgKHC2QFFHRXX37j/XgF2aBfvdmaQOg1jY2jBFqvwyzsDc8HvEWLBnVy+ZQc7DOw==
  template:
    metadata:
      name: grafana-admin-login
      namespace: monitoring
    type: Opaque