---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-login
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgANBUzRqjlNOLiGZlPZYHCL5A+tkackFEdkpJBxSNwEV2Nh7/QDtsL50o1gCdhNIqKZEWBlz7+jFs04LGG4gstIAPKI/8OoaR07kR8dK7cuh5PV6WE8TxgOkDwJO18OHlXmWKuhv21j5UxAXHLSlZsWryePizd/HTPVZZldIHUb09kEV/QB1nfG6uge/KGt2GxGuPqrK9iGpONcWMui5R5rCccpHdKGtTnBTAT3YmQjx8fanFQURGLsfTJo6BZo+AyY93U/O76qDK0hGOUYuILIlR8CXIHsPjkx+z6mgiYq/i2o1EyMUG/ctWCO8M05QCG3m/3DYruJX8ts892a/yys68DZjwzBEm9z8kceFaVRyCUDMRjnoKiA15DuPAsNo/FumKGTm/Do7NUFCXygzOD/UVJUBxkDkPa5TIPvjjaMc8MytZ1D2VdTr8ZbVDE0Ol+3RhVh3eIWt45m3jhDlyiwY7SmDheVY0ozglGSzjZ6bIoSC5YBQsxGYGH61Isd/naT9n4hnnv8sjGapE0V2FWS1SxT9RRmZ9EitBkZchY3oX5L0l619yTaI70vVdxKT9pkH30lwJvg0tFndmFg92CWn1KAMqiL2t/kOY0DjUOHAf4YBkPVF/4HSMOE//ZZHRk7AwfINvdwIJMJQ8HMiK9SmtMOpFnC57Xxz+FzBy+ywV4Z+fUuqnH/QV6db3rsBiu1daVcWLHd4lZR0irAaRqcSYR6Yw==
    admin-user: AgBvGF2TWcnaxpR1i7Cik56Ajvz+2VXA/cmdzwwKfDoYNCUblDTzWlKtqvXey7NvP5CeMEoXJF8MZMySRTrghw/b2jnosrCEa84aL3ms/33Y05MoKaCknTYCT23Z6d5Fk0fdHJ15L+si1/MRZWd8lWA6oDp3gfLQOc4pRz+AoydiDQOXabee1Viw5DuGg/HXoYdVTN3prR7qR0eZZg68UGCNOWcLG9jfcmVK03rPKD3/1pw6eIgbachJkoswR8yCxaCTUgR3lwcTbH2wzmv4KEm59a/rr4GwpcyziuYs6CwPb1M0YEtNuHjQCFEQU2Lp2HBWpok44V14ifbvxRN8jjb71bCa26SeBIto8iHcFvB5JbYIcg4vg/GDAwWU6YLQazOs1WHtadcR/nFfJFKfsyhAvyDbuO7k85fwtzwsWoSe17uV56q801aq5xKa7Bri914qaK7UL25aoiKBD4JfxtpSLacD0cDCnG3vDNksJz6FiRJsWwmRyy+4dmvzbTQJIfGXTp0QsVYurq9Nm8gNrOJvVoBOh715L3davS3YCTIiuw+BDZY+NbRpCEvj2ftsMBAPR+79VVSTgTqPBw2OWu+tIxvERB8YKNRrsOAg5gYD0qbskhBW8gLy0JFevNhMLBwtXJXzJsZ8ec9Rrof4kLV7Ob/lRyyTEQfA+shmjEUGEOpWujCKGPV9nkw2wfKPs6iCO/gpbw==
  template:
    metadata:
      name: grafana-admin-login
      namespace: monitoring
    type: Opaque